- name: Setup Inception
  hosts: prd_eus_server_01
  vars_files:
    - secrets.yml
    - vars.yml
  become: true

  tasks:
    - name: Check if Docker is installed
      command: docker --version
      register: docker_check
      ignore_errors: true
      changed_when: false

    - name: Install docker
      shell: curl -fsSL https://get.docker.com | sh
      when: docker_check.rc != 0

    - name: Copy inception directory
      copy:
        src: "{{ playbook_dir }}/../inception/"
        dest: "/home/{{ ansible_user }}/inception/"
        mode: "0755"

    - name: Install make
      apt:
        name: make
        state: present

    - name: Render .env file on the VM
      template:
        src: env.j2
        dest: /home/{{ ansible_user }}/inception/srcs/.env
        mode: "0600"

    - name: Build and run the containers
      shell: make -C /home/{{ ansible_user }}/inception/ up