server {
        listen 443 ssl;
        listen [::]:443 ssl;
        server_name HOSTNAME;

        ssl_certificate cert_path/cert.crt;
        ssl_certificate_key cert_path/cert.key;

        ssl_protocols TLSv1.2 TLSv1.3;

        root /var/www;

        index index.php index.html;

        location / {
                try_files $uri $uri/ /index.php;
        }

        location ~ \.php$ {
                include fastcgi.conf;
                fastcgi_pass wordpress:9000;
        }
}
